/**
 * Hand-written TypeScript mirrors of the Postgres schema in
 * `db/migrations/0001_init.sql`. Per AGENTS.md: schema changes ship in
 * the same commit as updates to this file.
 *
 * Timestamps come over the wire from Supabase as ISO-8601 strings.
 */

export type Uuid = string;
export type IsoTimestamp = string;

export type MessageRole = "user" | "assistant" | "system";
export type HighlightSource = "user" | "ai";

export interface UserRow {
  id: Uuid;
  display_name: string;
  color: string;
  created_at: IsoTimestamp;
  last_seen_at: IsoTimestamp;
}

export interface ProjectRow {
  id: Uuid;
  name: string;
  room_code: string;
  master_context: string;
  created_by: Uuid | null;
  created_at: IsoTimestamp;
  updated_at: IsoTimestamp;
}

export interface SessionRow {
  id: Uuid;
  project_id: Uuid;
  parent_session_id: Uuid | null;
  fork_point_message_id: Uuid | null;
  session_target: string;
  label: string | null;
  tags: string[];
  summary: string;
  /**
   * LLM-distilled highlights from ancestor sessions, aligned to
   * `session_target`. Set when creating a fork or combined-context session.
   */
  smart_context?: string;
  created_by: Uuid | null;
  created_at: IsoTimestamp;
  updated_at: IsoTimestamp;
  last_activity_at: IsoTimestamp;
  message_count: number;
  is_archived: boolean;
  /**
   * Lock fields (migration 0002): set while one user is actively
   * sending a message in this session; null otherwise. Other users in
   * the same session see disabled inputs while a lock is held.
   */
  pending_user_id: Uuid | null;
  pending_since: IsoTimestamp | null;
}

export interface MessageRow {
  id: Uuid;
  session_id: Uuid;
  role: MessageRole;
  author_id: Uuid | null;
  content: string;
  model: string | null;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  created_at: IsoTimestamp;
  edited_at: IsoTimestamp | null;
  is_deleted: boolean;
  /**
   * `PersistedAgentTrace` snapshot of the visible "clinical team" run that
   * produced this message. Populated only for assistant rows generated by
   * the agent pipeline (chat). Older rows / non-agent paths leave it null.
   * Added in migration 0007_message_agent_trace.sql.
   */
  agent_trace?: unknown;
}

/**
 * One row per (child → parent) edge in the DAG. Regular single-parent
 * forks have exactly one row; combined-context nodes have two or more.
 * Added in migration 0004_session_parents.sql.
 */
export interface SessionParentRow {
  session_id: Uuid;
  parent_id: Uuid;
}

export interface SessionParticipantRow {
  session_id: Uuid;
  user_id: Uuid;
  joined_at: IsoTimestamp;
  last_active_at: IsoTimestamp;
  message_count: number;
}

export interface HighlightRow {
  id: Uuid;
  session_id: Uuid;
  message_id: Uuid | null;
  content: string;
  note: string | null;
  source: HighlightSource;
  created_by: Uuid | null;
  created_at: IsoTimestamp;
}
